name: Bug Report 
description: Found a bug report and want to report it! 

title: "[Bug]: "
labels: ["bug"]
assignees:
  - hectoritr
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false    
  - type: input
    id: branch
    attributes:
      label: Current Branch
      description: What branch are you currently working on?
      placeholder: master/development
     validations:
      required: true
  - type: input
    id: flutterversion
    attributes:
      label: Flutter version
      description: What Flutter & Dart version do you have?
      placeholder: 3.x.x
     validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: How did it happen?
      description: Please tell us step by step what commands did you use to get here
      placeholder: flutter clean ... pub get ... 
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true  
  - type: dropdown
    id: browsers
    attributes:
      label: Where are you seeing the problem on?
      multiple: true
      options: 
        - Chrome (WebApp)
        - Android
        - iOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/OTTAA-Project/.github/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
