blank_issues_enabled: true
contact_links:
  - name: OTTAA's Community Support
    url: https://discord.gg/UsYC8nKX
    about: Please join our Discord Community Support channel to engage with us faster.
  
  - name: OTTAA's Security Bug Bounty
    url: mailto:support@ottaaproject.com
    about: Please contact inmediately with en email about "Security/Vulnerability" to be eligible for a bounty up to 2 ETH.
    
   
